### ISSUE TITLE
Latest versions do not load and return to the Bios

### ISSUE THREAD

**Issue by DukeJP** [pcm720/nhddl#16]
Although before I updated by simply replacing files, this time I wanted to be sure and did a clean installation.
When loading Nhddl, in the list of modules the first one says "smap_udpbd ; failed to initialize arguments, skipping module"
Then, in the part under "initializing BDM devices", it says "error: could not find Neutrino.elf"

Obviously those files are there, double check. 

I'm loading from memory card 2 (mc1 in ulaunchelf), and using internal hard drive, as I've always done.

I'm using the latest versions of Neutrino and Nhddl, with support for the new mode 7 "buffer overrun fix"
https://github.com/rickgaiser/neutrino/releases/download/latest/neutrino-20241126-11757275.7z

I don't know who to "blame" for this, Nhdd or Neutrino, I apologize if I'm posting wrong here.

**Comment by pcm720** [comment]
Are you using the latest nightly?
https://github.com/pcm720/nhddl/releases/download/nightly/nhddl-v0.3.0-58-g6bf3107.zip

**Comment by pcm720** [comment]
Oh well...
I can replicate it and I'll look into it. Lots of weird stuff happening lately....
For now you can try placing neutrino with its folders on your HDD in `neutrino/` or use the last stable build with custom title config for Donkey Xote. It just needs to contain `gc: 7`.

**Comment by pcm720** [comment]
Ok, I fixed this issue in 
https://github.com/pcm720/nhddl/releases/download/nightly/nhddl-v0.3.0-59-g598319e.zip

Now NHDDL skips loading MX4SIO module if it sees that a memory card is present in slot 2

**Comment by DukeJP** [comment]
now it works perfectly. the message related to smap_udpbd still appears, but other than that it loads without problems.

**Comment by pcm720** [comment]
Great!
Yeah, seeing `smap_udpbd: failed to initialize arguments, skipping module` is okay if you don't have SYS-CONF/IPCONFIG.DAT on your memory cards and `udpbd_ip` is not set in nhddl.yaml. If you do have IPCONFIG.DAT on your memory card, though, this is possibly a bug. But it reads IPCONFIG.DAT on my machine.

By the way, you can decrease initialization times by adding `mode: ata` to `nhddl.yaml`, it will skip all unnecessary modules, including UDPBD, and reduce the time it waits for BDM devcies.
